### PR TITLE
fix: 🐛 profile picture layout by using height: fit-content for container

### LINKED ISSUE #12: Improve profile picture layout
At the moment, the profile pictures at the top, overflow when the screen is too narrow, or there's too many pictures!

This issue will need you to go through the CSS and make sure the website is responsive!

Screenshot 2021-09-30 at 14 21 19
Screenshot 2021-09-30 at 14 21 58

### PR DESCRIPTION
**Pull request by Minh-ctrl**
✅ Closes: #12

## Please, go through these steps before you submit a PR.

- [X ] My Pod Leader knows I'm working on this Pull Request
- [ X] I've explained what the Pull Request is adding.
- [ X] I've explained why this is important.

### CODE REVIEW

**Comment by Minh-ctrl** [comment]
I've set the height of the .profile and .profile-picture to `fit-content` and also set a specific max-width and height of the images to be 350px which fixed the issue

image

image

image

**Review by sohamsshah — COMMENTED** [review]
Hey @Minh-ctrl , this looks great 💯

I had one small thing to brainstorm and get your views from design standpoint:
- In smaller screens, would it be better if we can make images' width smaller. Basically the image size can be made responsive. Reason: It can be better to have 2X2 sort of Images in the Smaller Screens as 4 Images vertically in one column might look a little bit long for smaller screens. What do you think?

Thank you!

**Comment by Minh-ctrl** [comment]
> Hey @Minh-ctrl , this looks great 💯
> 
> I had one small thing to brainstorm and get your views from design standpoint:
> 
> * In smaller screens, would it be better if we can make images' width smaller. Basically the image size can be made responsive. Reason: It can be better to have 2X2 sort of Images in the Smaller Screens as 4 Images vertically in one column might look a little bit long for smaller screens. What do you think?
> 
> Thank you!

Hey @sohamsshah! 

Thanks for the feedback! I didn't think about this at all when I implemented the solution 😆 .

For the solution i think it's a simple media query implementation. At a certain width size we can adjust the image to a certain size so that the users would have less to scroll.  I've set the media query to be around 400px
Here's the code:
`  @media only screen and (max-width: 400px) {
    img {
      width: 150px;
      height: 150px;
    }
  }`

Thanks for your suggestion, i think this issue will really matter once we add all 20 of us onto the portfolio so it's good to catch it early 😄 .

**Comment by Minh-ctrl** [comment]
> Hey @Minh-ctrl , this looks great 💯
> 
> I had one small thing to brainstorm and get your views from design standpoint:
> 
> * In smaller screens, would it be better if we can make images' width smaller. Basically the image size can be made responsive. Reason: It can be better to have 2X2 sort of Images in the Smaller Screens as 4 Images vertically in one column might look a little bit long for smaller screens. What do you think?
> 
> Thank you!

Hey @sohamsshah! that's a great suggestion!

**Review by sohamsshah — APPROVED** [review]
Amazing addition! 🚀

P.S. Just a small suggestion. When contributing, it is a good practice to create a separate feature branch and then create a PR (instead of comparing from main. The reason being we want to keep our fork's main branch clean and sync with the upstream's main). Basically it can be `Minh-ctrl wants to merge x commits into MLH-Fellowship:main from Minh-ctrl:fix/profile-pic-layout`.

**Pull request merged**
